### ISSUE TITLE
Ajax calls with empty body

### ISSUE THREAD

**Issue by JeroenVeghel** [Leuchtfeuer/locate#22]
Hello,

I'm making an ajax request which get redirected by this plugin. The problem is that postdata is missing in the redirected call. Is that a known issue? Or am I missing something in my configuration?

**Comment by elbebass** [comment]
Sorry for the late reply. If I understood your problem correctly, you are making an AJAX call to a specific page and/or function passing POST data. This is intercepted by the locate extension and redirected.
This is generally desired and not otherwise wanted by specification (https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html). 
But what should be easy to do and solve your problem would be to set up a condition on the target page of the Ajax call.
In our documentation we have described how to switch on the extension for single pages via condition [see https://docs.typo3.org/p/leuchtfeuer/locate/master/en-us/Admin/Index.html#enabling-this-extension]. Similarly, I would simply turn off our extension on the target page of your Ajax call, which should then fix your problem or not execute the redirect at all.

I hope this helps.
